spring:
  application:
    name: ch4-code
  datasource:
    url: jdbc:postgresql://localhost:5432/post_db
    username: root
    password: pass1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
